name: Mypy Static Type Checking

on: [ "push", "pull_request" ]

env:
  PROJECT_DIR: "aio_mqtt"

jobs:
  ruff-lint:
    name: Run mypy on multiple Python versions
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
          ruff --version

      - name: Run mypy
        run: |
          ruff check "${PROJECT_DIR}"